# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_album_album_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
